# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "vpc-terraform-eds-lab-state-2"
    dynamodb_table = "eds-lab-tf-lock-table-2"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
