# An advanced example of ClusterConfig object with customised nodegroups:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ex-eks-v1-23
  region: us-east-1

vpc:
  id: "vpc-0f7b6198b3f045e36"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.217.0.0/18"       # (optional, must match CIDR used by the given VPC)
  #sharedNodeSecurityGroup: "sg-0990e8e61e561181b"
  securityGroup: "sg-0ab799946a693a6c3"
  subnets:
    private:
      us-east-1a:
        id: "subnet-0d756062fb1a1b8f4"
        cidr: "10.217.0.0/24" # (optional, must match CIDR used by the given subnet)

      us-east-1b:
        id: "subnet-02a050678bf859b5b"
        cidr: "10.217.4.0/24"  # (optional, must match CIDR used by the given subnet)

      us-east-1c:
        id: "subnet-0a29e8d328878cf49"
        cidr: "10.217.8.0/24"   # (optional, must match CIDR used by the given subnet)

managedNodeGroups:
  - name: type-t3
    instanceType: t3.large
    minSize: 1
    maxSize: 8
    volumeSize: 20
    volumeType: gp3
    #AMI eks 1.21
    #ami: ami-0878b75b482934e1f
    amiFamily: AmazonLinux2
    # forces the use of IMDSv2 tokens
    disableIMDSv1: true
    labels:
      prod: "true"
      rancher: "true"
    #targetGroupARNs:
    #  - arn:aws:elasticloadbalancing:eu-west-2:01234567890:targetgroup/target-group-1/abcdef0123456789
    iam:
      attachPolicyARNs:
    #    - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
    #    - arn:aws:iam::aws:policy/AmazonEBSCSIDriverPolicy
    #    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    #    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    #    - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
    #    certManager: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        cloudWatch: true
    privateNetworking: true
    # cluster AZs must be set explicitly for single AZ nodegroup example to work
    availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]