---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-prd
  region: sa-east-1

vpc:
  id: "vpc-0910478988f93e84b"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.221.0.0/21"       # (optional, must match CIDR used by the given VPC)
  securityGroup: "sg-093aeb362fbe074cc"
  subnets:
    private:
      sa-east-1a:
        id: "subnet-0dfe5d80e17b090e4"
        cidr: "10.221.0.0/24" # (optional, must match CIDR used by the given subnet)

      sa-east-1b:
        id: "subnet-0dd5f28182e50d358"
        cidr: "10.221.1.0/24"  # (optional, must match CIDR used by the given subnet)

      sa-east-1c:
        id: "subnet-026f64733075528fd"
        cidr: "10.221.2.0/24"   # (optional, must match CIDR used by the given subnet)


nodeGroups:
  - name: type-t3
    instanceType: t3.xlarge
    minSize: 3
    maxSize: 8
    volumeSize: 30
    volumeType: gp3
    #AMI eks 1.21
    ami: ami-06837e22b79c3b522
    amiFamily: AmazonLinux2
    # forces the use of IMDSv2 tokens
    disableIMDSv1: true
    labels:
      prod: "true"
      ingress: "true"
    targetGroupARNs:
      - arn:aws:elasticloadbalancing:eu-west-2:01234567890:targetgroup/target-group-1/abcdef0123456789
    iam:
      withAddonPolicies:
        autoScaler: true
