# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Managed_by  = "Terraform"
      Environment = "Prod"
      map-migrated= "d-server-02dzarjfi0ibj1"
    }
  }
}
